library(shiny)
library(plotly)
library(shinyjs)
library(shinyalert)
library(leaflet)
library(leaflet.extras)
library(retistruct)
library(viridis)
library(tidyr)
library(gridExtra)
library(raster)
library(ggplot2)
library(rgdal)
library(plyr)
library(TTR)
library(caTools)
library(RColorBrewer)
library(LearnGeom)
library(scales)
library(numDeriv)
library(retistruct)
library(gtable)
library(grid)
library(zoo)
library(smoothr)
library(PBSmapping)
library(velox)
library(spatstat)
library(smoothr)

source('Functions/offset_from_crest_base_manual.R', local = TRUE)
source('Functions/offset_from_crest_base_algorithm.R', local = TRUE)
source('Functions/function_offset_from_crest_base_manual.R', local = TRUE)
source('Functions/function_offset_from_crest_base_algorithm.R', local = TRUE)
source('Functions/function_crest_base_algorithm.R', local = TRUE)

source('Functions/fault_scarp_app_efficient.R', local = TRUE)
source('Functions/rms_difs.R', local = TRUE)
source('Functions/plots.R', local = TRUE)
source('Functions/single_plot_comp.R', local = TRUE)
source('Functions/multi_plot_comp.R', local = TRUE)

source('Functions/dist4plot_UTM.R', local = TRUE)   # DISTANCE ALONG PERP PROFILES
source('Functions/points_to_line.R', local = TRUE)  # POINTS TO LINES
source('Functions/create_cropped_raster_hillshade.R', local = TRUE)
source('Functions/create_profiles_segments.R', local = TRUE)
source('Functions/create_profiles_segments_fast.R', local = TRUE)
source('Functions/fault_scarp2_new.R', local = TRUE)

source('Functions/fault_rds.R', local = TRUE) 
source('Functions/fault_rds.R', local = TRUE) 
